// <auto-generated />
using System;
using LevelApp.DAL.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LevelApp.DAL.Migrations
{
    [DbContext(typeof(MySqlContext))]
    [Migration("20190616105309_001_CreateUsersTable")]
    partial class _001_CreateUsersTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LevelApp.DAL.Models.CoreUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CreatedBy");

                    b.Property<DateTime?>("DateCreatedUtc");

                    b.Property<DateTime?>("DateDeletedUtc");

                    b.Property<DateTime?>("DateModifiedUtc");

                    b.Property<long?>("DeletedBy");

                    b.Property<long?>("ModifiedBy");

                    b.Property<string>("Password");

                    b.Property<string>("Token");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("CoreUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
